"""added StatHistory model for crontab script

Revision ID: 602f221593b2
Revises: 27b8b66bc0a7
Create Date: 2023-05-04 12:41:29.599974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602f221593b2'
down_revision = '27b8b66bc0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stathistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], name=op.f('fk_stathistory_habit_id_habits')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stathistory_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habitstats', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habitstats', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('stathistory')
    # ### end Alembic commands ###
