"""test model

Revision ID: 624eee6571a0
Revises: 
Create Date: 2023-04-25 13:03:12.655889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624eee6571a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
